const USERID_MAX = 30; // 유저 아이디 최소
const USERID_MIN = 4; // 유저 아이디 최대
const USERNAME_MAX = 30; // 유저 이름 최소
const USERNAME_MIN = 1; // 유저 이름 최대
const NUMOFBIRTH = 8; // 생일 숫자 개수
const COUNTRY_DEFAULT = "ko"; // 국가
const LANGUAGE_DEFAULT = "ko-KR"; // 언어
const INTRO_MAX = 150; // 자기 소개 최대
const EMAIL_SPECIAL_CHARACTERS =
  "\\!\\#\\$\\%\\&\\'*\\+\\/\\=?\\^_\\`\\{\\|\\}\\~";
const VERIFICATION_EXPIRES = "3m";
const USERID_SPECIAL_CHARACTERS = "_";
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID!;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET!;
const GOOGLE_REDIRECT_URI = process.env.GOOGLE_REDIRECT_URI!;
const KAKAO_REDIRECT_URI = process.env.KAKAO_REDIRECT_URI!;
const KAKAO_REST_API_KEY = process.env.KAKAO_REST_API_KEY!;
const NAVER_CLIENT_ID = process.env.NAVER_CLIENT_ID!;
const NAVER_CLIENT_SECRET = process.env.NAVER_CLIENT_SECRET!;
const NAVER_REDIRECT_URI = process.env.NAVER_REDIRECT_URI!;
const BASE_URL = process.env.BASE_URL!;
const REFRESHTOKEN_EXPIRES = 60 * 60;
const ACCESSTOKEN_EXPIRES = 60;
// 로그인 기록 만료 기간
const LOGINRECORD_EXPIRES = 60 * 60 * 24 * 30 * 6;
// 로그인 실패 만료 기간
const LOGINFAILURE_EXPIRES = 60 * 60 * 24 * 30 * 6;
const BRUTE_FORCE_THRESHOLD = 5; // BruteForce 판별 기준 (최근 특정 시간 내 실패 횟수)
const ACCOUNT_LOCK_THRESHOLD = 5; // 계정 잠금 기준 (전체 실패 횟수)
const LOGIN_FAILURE_TIME_WINDOW_MS = 60 * 60 * 1000; // 로그인 실패 시간 범위 (1시간)
const API_CALL_TIMEOUT = 30 * 1000;

export {
  COUNTRY_DEFAULT,
  INTRO_MAX,
  LANGUAGE_DEFAULT,
  USERID_MAX,
  USERID_MIN,
  USERNAME_MAX,
  USERNAME_MIN,
  NUMOFBIRTH,
  EMAIL_SPECIAL_CHARACTERS,
  VERIFICATION_EXPIRES,
  USERID_SPECIAL_CHARACTERS,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,
  KAKAO_REDIRECT_URI,
  KAKAO_REST_API_KEY,
  NAVER_CLIENT_ID,
  NAVER_CLIENT_SECRET,
  NAVER_REDIRECT_URI,
  BASE_URL,
  REFRESHTOKEN_EXPIRES,
  ACCESSTOKEN_EXPIRES,
  LOGINRECORD_EXPIRES,
  LOGINFAILURE_EXPIRES,
  BRUTE_FORCE_THRESHOLD,
  ACCOUNT_LOCK_THRESHOLD,
  LOGIN_FAILURE_TIME_WINDOW_MS,
  API_CALL_TIMEOUT,
};
